name: Release Please

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      releaseAs:
        description: 'Release as version'
        required: true
        type: string

permissions:
  contents: write
  id-token: write
  packages: write
  pull-requests: write

jobs:
  release-please:
    uses: voxpelli/ghatemplates/.github/workflows/release-please.yml@main
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    with:
      releaseAs: ${{ inputs.releaseAs }}
      packageName: "@voxpelli/typed-utils"
      bootstrapSha: aa2baf047fe00b7892ee5edd932fb5b506f11a8d
